### ISSUE TITLE
Load commercial breaks not working in 0.14

### ISSUE THREAD

**Issue by RXM307** [roadrunner6/mythcut#1]
Load commercial breaks not working in 0.14, I know you know this is still not working, just thought I'd make it official

**Comment by roadrunner6** [comment]
Am 20.04.2012 00:06, schrieb RXM307:

> Load commercial breaks not working in 0.14, I know you know this is still not working, just thought I'd make it official

Sorry, I know it, but I'm quite busy right now. Will have a look, 
hopefully soon!

**Comment by roadrunner6** [comment]
Loading the commercial breaks as cutlist now works again

**Comment by RXM307** [comment]
Thanks is working fine but got this error on a recording

```
    Query: expected one result, got none!       


    Array
```

(
    [0] => Array
        (
            [file] => /var/www/mythcut/lib/Movie.php
            [line] => 360
            [function] => Result
            [class] => Query
            [type] => ->
            [args] => Array
                (
                )

```
    )

[1] => Array
    (
        [file] => /var/www/mythcut/lib/Movie.php
        [line] => 133
        [function] => findNearestKeyframeMark
        [class] => Movie
        [type] => ->
        [args] => Array
            (
                [0] => 150178
                [1] => -1
            )

    )

[2] => Array
    (
        [file] => /var/www/mythcut/lib/MovieHandler.php
        [line] => 45
        [function] => getSeekTable
        [class] => Movie
        [type] => ->
        [args] => Array
            (
            )

    )

[3] => Array
    (
        [file] => /var/www/mythcut/lib/MovieHandler.php
        [line] => 33
        [function] => handleActions
        [class] => MovieHandler
        [type] => ->
        [args] => Array
            (
            )

    )

[4] => Array
    (
        [file] => /var/www/mythcut/index.php
        [line] => 167
        [function] => __construct
        [class] => MovieHandler
        [type] => ->
        [args] => Array
            (
            )

    )
```

)

**Comment by RXM307** [comment]
must have been something wrong with the commflag list for this recording I reran mythcommflag on this recording and it was able to load, you can close this issue, Thank You
